wordpress_api.blogger.getUsersBlogs:
    path: /xmlrpc/blogger.getUsersBlogs
    defaults:
        _controller: bd_wordpress_api.controller.users:getUsersBlogs

wordpress_api.blogger.getUserInfo:
    path: /xmlrpc/blogger.getUserInfo
    defaults:
        _controller: bd_wordpress_api.controller:getProfile

wordpress_api.blogger.getPost:
    path: /xmlrpc/blogger.getPost/{postId}
    defaults:
        _controller: bd_wordpress_api.controller.post:getPost

wordpress_api.blogger.deletePost:
    path: /xmlrpc/blogger.deletePost/{postId}
    defaults:
        _controller: bd_wordpress_api.controller.post:deletePost

wordpress_api.mt.getRecentPostTitles:
    path: /xmlrpc/mt.getRecentPostTitles
    defaults:
        _controller: bd_wordpress_api.controller.post:getRecentPosts

wordpress_api.mt.getCategoryList:
    path: /xmlrpc/mt.getCategoryList
    defaults:
        _controller: bd_wordpress_api.controller:getCategoryList

wordpress_api.mt.setPostCategories:
    path: /xmlrpc/mt.setPostCategories/{postId}
    defaults:
        _controller: bd_wordpress_api.controller:setPostCategories

wordpress_api.mt.getPostCategories:
    path: /xmlrpc/mt.getPostCategories/{postId}
    defaults:
        _controller: bd_wordpress_api.controller:getPostCategories

wordpress_api.mt.supportedMethods:
    path: /xmlrpc/mt.supportedMethods
    defaults:
        _controller: bd_wordpress_api.controller:getSupportedMethods

wordpress_api.metaWeblog.getCategories:
    path: /xmlrpc/metaWeblog.getCategories
    defaults:
        _controller: bd_wordpress_api.controller:getCategoryList

wordpress_api.metaWeblog.getRecentPosts:
    path: /xmlrpc/metaWeblog.getRecentPosts
    defaults:
        _controller: bd_wordpress_api.controller.post:getRecentPosts

wordpress_api.metaWeblog.newPost:
    path: /xmlrpc/metaWeblog.newPost
    defaults:
        _controller: bd_wordpress_api.controller.post:newPost

wordpress_api.metaWeblog.editpost:
    path: /xmlrpc/metaWeblog.editPost/{postId}
    defaults:
        _controller: bd_wordpress_api.controller.post:editPost

wordpress_api.metaWeblog.deletePost:
    path: /xmlrpc/metaWeblog.deletePost/{postId}
    defaults:
        _controller: bd_wordpress_api.controller.post:deletePost

wordpress_api.metaWeblog.getPost:
    path: /xmlrpc/metaWeblog.getPost/{postId}
    defaults:
        _controller: bd_wordpress_api.controller.post:getPost

wordpress_api.metaWeblog.getPostCategories:
    path: /xmlrpc/metaWeblog.getPostCategories
    defaults:
        _controller: bd_wordpress_api.controller:getPostCategories

wordpress_api.system.listMethods:
    path: /xmlrpc/system.listMethods
    defaults:
        _controller: bd_wordpress_api.controller:getSupportedMethods

wordpress_api.wp.getUsersBlogs:
    path: /xmlrpc/wp.getUsersBlogs
    defaults:
        _controller: bd_wordpress_api.controller.users:getUsersBlogs

wordpress_api.wp.getOptions:
    path: /xmlrpc/wp.getOptions
    defaults:
        _controller: bd_wordpress_api.controller.options:getOptions

wordpress_api.wp.getProfile:
    path: /xmlrpc/wp.getProfile
    defaults:
        _controller: bd_wordpress_api.controller:getProfile

wordpress_api.wp.getComments:
    path: /xmlrpc/wp.getComments
    defaults:
        _controller: bd_wordpress_api.controller:getComments

wordpress_api.wp.getPostFormats:
    path: /xmlrpc/wp.getPostFormats
    defaults:
        _controller: bd_wordpress_api.controller:getPostFormats

wordpress_api.wp.getCategories:
    path: /xmlrpc/wp.getCategories
    defaults:
        _controller: bd_wordpress_api.controller.wordpress:getCategories

wordpress_api.wp.getMediaItem:
    path: /xmlrpc/wp.getMediaItem/{mediaItemId}
    defaults:
        _controller: bd_wordpress_api.controller.media:getMediaItem

wordpress_api.wp.getMediaLibrary:
    path: /xmlrpc/wp.getMediaLibrary
    defaults:
        _controller: bd_wordpress_api.controller.media:getMediaLibrary

wordpress_api.wp.uploadFile:
    path: /xmlrpc/wp.uploadFile
    defaults:
        _controller: bd_wordpress_api.controller.media:uploadFile

wordpress_api.wp.deletePost:
    path: /xmlrpc/wp.deletePost/{postId}
    defaults:
        _controller: bd_wordpress_api.controller.post:deletePost

wordpress_api.wp.getPost:
    path: /xmlrpc/wp.getPost/{postId}
    defaults:
        _controller: bd_wordpress_api.controller.post:getPost

wordpress_api.wp.editpost:
    path: /xmlrpc/wp.editPost
    defaults:
        _controller: bd_wordpress_api.controller.post:editPost
