parameters:
    bd_wordpress_api.controller.class: BD\Bundle\WordpressAPIBundle\Controller\DefaultController
    bd_wordpress_api.controller.options.class: BD\Bundle\WordpressAPIBundle\Controller\Options
    bd_wordpress_api.controller.wordpress.class: BD\Bundle\WordpressAPIBundle\Controller\Wordpress
    bd_wordpress_api.controller.media.class: BD\Bundle\WordpressAPIBundle\Controller\Media
    bd_wordpress_api.controller.post.class: BD\Bundle\WordpressAPIBundle\Controller\Post
    bd_wordpress_api.controller.users.class: BD\Bundle\WordpressAPIBundle\Controller\Users

    bd_wordpress_api.response_decorator.dispatcher.class: BD\Bundle\WordpressAPIBundle\ResponseDecorator\ResponseDecoratorDispatcher

    bd_wordpress_api.authentication_dispatcher.class: BD\Bundle\WordpressAPIBundle\Authentication\AuthenticationDispatcher
    bd_wordpress_api.authentication_request_listener.class: BD\Bundle\WordpressAPIBundle\EventListener\AuthenticationRequestListener

services:
    bd_wordpress_api.controller:
        class: %bd_wordpress_api.controller.class%
        arguments:
            - @ezpublish.api.repository
            - @bd_wordpress_api.service.category
            - @bd_wordpress_api.service.post

    bd_wordpress_api.controller.options:
        class: %bd_wordpress_api.controller.options.class%

    bd_wordpress_api.controller.wordpress:
        class: %bd_wordpress_api.controller.wordpress.class%
        arguments:
            - @bd_wordpress_api.service.category

    bd_wordpress_api.controller.media:
        class: %bd_wordpress_api.controller.media.class%
        arguments:
            - @bd_wordpress_api.service.media

    bd_wordpress_api.controller.post:
        class: %bd_wordpress_api.controller.post.class%
        arguments:
            - @bd_wordpress_api.service.post
            - @bd_wordpress_api.response_decorator.dispatcher

    bd_wordpress_api.controller.users:
        class: %bd_wordpress_api.controller.users.class%

    bd_wordpress_api.response_decorator.dispatcher:
        class: %bd_wordpress_api.response_decorator.dispatcher.class%

    bd_wordpress_api.authentication_request_listener:
        class: %bd_wordpress_api.authentication_request_listener.class%
        arguments: [@bd_wordpress_api.authentication_dispatcher]
        tags:
            - { name: kernel.event_subscriber }

    bd_wordpress_api.authentication_dispatcher:
        class: %bd_wordpress_api.authentication_dispatcher.class%